# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JulongSoftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JulongSoftDemo
  pod 'Alamofire', '~> 4.2.0'
  pod 'SwiftyJSON'




end
